"""One-time migration of user-visible labels; internal identifiers stay stable."""
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
MAPPING={
'Étalement</option>':'After spreading</option>', 'Fusion</option>':'After melting</option>',
"+' à '+":"+' to '+", "('Référence','reference')":"('Reference','reference')", "('Analyse',snapshot['run'])":"('Analysis',snapshot['run'])",
"'Plan '":"'Plane '", 'Minimum persistence : ':'Minimum persistence: ',
'Image de cette couche absente.':'Image unavailable for this layer.', 'Dimensions différentes : comparaison indisponible.':'Different image dimensions: comparison unavailable.',
'Cadrage hors de l’image.':'Crop outside the image.', 'Photo de couche':'Layer photograph', 'Image indisponible : ':'Image unavailable: ',
'Intensité et persistance du score invalides.':'Invalid score intensity or persistence.', 'Ordre de revue inconnu.':'Unknown review order.',
'La persistance doit être un entier entre 1 et 10 000.':'Persistence must be an integer between 1 and 10,000.',
'Dossier source introuvable.':'Source folder not found.', 'Couche antérieure à l’origine configurée : ':'Layer precedes the configured origin: ',
'Doublon caméra/étape/couche : ':'Duplicate camera/stage/layer: ', '. Corriger le motif ou séparer les jobs.':'. Correct the filename pattern or separate the jobs.',
'Aucune image reconnue. Vérifier le modèle de nom et les alias d’étapes.':'No images recognized. Check the filename pattern and stage aliases.',
'Une caméra, éclairage a. Couches et étapes documentées.':'One camera, illumination a. Documented layers and stages.',
'Images locales':'Local images', 'ORNL · 64 cylindres · 200 photos':'ORNL · 64 cylinders · 200 photos',
'Job distinct : couches 2–101, 20 µm. Photos après étalement et après fusion, pixels originaux convertis sans perte en PNG.':'Separate build: layers 2–101, 20 µm. Post-spreading and post-melting photographs, original pixels converted losslessly to PNG.',
'Un job : couches 70–169, 100 µm. Canaux visibles sans annotations, corrigés par les producteurs (éclairage et perspective). Miroir public Hugging Face ; hauteur relative à l’indice 0.':'One build: layers 70–169, 100 µm. Unannotated visible channels, corrected by the producers for illumination and perspective. Public Hugging Face mirror; height relative to index 0.',
'Un job autonome : niveau de gris initial, changements et dérives au fil des acquisitions. Étapes et hauteurs non attribuées.':'Single-job analysis: initial gray level, changes and drift across acquisitions. Stages and physical heights are not assigned.',
'Indiquer le chemin absolu d’un dossier existant sur cet ordinateur.':'Enter the absolute path to an existing folder on this computer.',
'Nom de bibliothèque trop long.':'Library name is too long.', 'Dossier local référencé sans copier les images.':'Local folder referenced without copying its images.',
'Séquence inconnue.':'Unknown sequence.', 'Décision inconnue.':'Unknown decision.', 'Indication de départ introuvable.':'Starting indication not found.',
'Indication introuvable dans ce job.':'Indication not found in this job.', 'Indication modifiée : rechargez-la avant de décider.':'This indication has changed. Reload it before saving a decision.',
'Image introuvable dans ce job.':'Image not found in this job.', 'Image hors bibliothèque.':'Image outside the library.',
'Cette image ne correspond pas aux acquisitions comparées.':'This image does not match the compared acquisitions.', 'Acquisition non mesurée.':'Acquisition not measured.',
'Lancez une analyse pour préparer l’empilement.':'Run an analysis to prepare the stack.', 'Séquence 3D inconnue.':'Unknown 3D sequence.', 'Caméra inconnue.':'Unknown camera.',
'Aucune acquisition mesurée.':'No measured acquisitions.',
'Le motif doit contenir camera, layer et phase comme groupes nommés.':'The pattern must include camera, layer and phase as named groups.',
' doit être un entier.':' must be an integer.', 'tile_px >= 2 et 3 <= warmup <= history <= 101 requis.':'Required: tile_px >= 2 and 3 <= warmup <= history <= 101.',
' doit être positif et fini.':' must be positive and finite.', "drift_alpha <= 1 et hauteur d'origine finie requises.":'Required: drift_alpha <= 1 and a finite origin height.',
'Les étapes cibles sont etalement et fusion.':'Target stage identifiers are etalement and fusion.',
'Sélectionner etalement, fusion ou les deux pour l’analyse.':'Select etalement, fusion or both for analysis.', "Alias d'étapes ambigus.":'Ambiguous stage aliases.',
'Chaque ROI doit être [x0,y0,x1,y1] en pixels entiers.':'Each ROI must contain integer pixel coordinates [x0,y0,x1,y1].',
'Les paramètres sont figés dans ce projet. Choisir un nouveau dossier de résultats pour les modifier.':'Settings are fixed in this project. Choose a new output folder to change them.',
'Import ambigu ou modifié : {fatal} problème(s). Détails dans la commande status.':'Ambiguous or changed import: {fatal} issue(s). See the status command for details.',
'Aucune image reconnue. Adapter filename_regex aux chemins relatifs réels.':'No recognized images. Adapt filename_regex to the actual relative paths.',
'Une image 8 bits requiert intensity_white_level=255.':'An 8-bit image requires intensity_white_level=255.',
'Image 16 bits : préciser une échelle fixe intensity_white_level (ex. 65535).':'16-bit image: set a fixed intensity_white_level (e.g. 65535).',
"Des intensités sortent de l'échelle fixe configurée.":'Image intensities exceed the configured fixed scale.', "Mode d'image non pris en charge : {image.mode}.":'Unsupported image mode: {image.mode}.',
"La ROI sort des dimensions de l'image.":'The ROI is outside the image dimensions.', 'Cadrage invalide.':'Invalid crop.',
'Gris des 20 premières images par caméra et étape de ce job. Ces images ne sont pas déclarées saines.':'Gray level from the first 20 images per camera and stage of this job. These images are not assumed to be defect-free.',
"Placer les résultats hors du dossier d'images source.":'Store results outside the source image folder.', 'Fichier modifié après indexation.':'File changed after indexing.',
'Analyse du job seul, par caméra et étape. Aucune annotation ni autre job utilisé.':'Single-job analysis, per camera and stage. No annotations or other jobs used.',
"Décisions provenant d'un autre projet.":'Decisions belong to another project.', 'Statut de revue inconnu.':'Unknown review status.', 'Le commentaire doit être du texte.':'The comment must be text.',
'Indication inconnue.':'Unknown indication.', "L'indication a évolué depuis la création de la page : régénérer la revue.":'The indication has changed since this page was created. Regenerate the review.',
'Une analyse doit contenir exactement un job.':'An analysis must contain exactly one job.', 'Compteurs d’acquisition en doublon dans ce job.':'Duplicate acquisition counters in this job.',
'Intervalle d’acquisition invalide.':'Invalid acquisition interval.',
'Niveau de gris moyen des 20 premières acquisitions de chaque séquence. Ces images ne sont pas déclarées saines.':'Mean gray level from the first 20 acquisitions in each sequence. These images are not assumed to be defect-free.',
'La calibration ne correspond pas à ce job et à ce cadrage.':'Calibration does not match this job and crop.',
'Changements et dérives dans ce job. Les annotations et les autres jobs ne sont pas utilisés. Étapes physiques non identifiées.':'Changes and drift within this job. Annotations and other jobs are not used. Physical stages are unidentified.',
'Le contraste de reconstruction doit être compris entre 1 et 8.':'Reconstruction contrast must be between 1 and 8.', 'Cadrage de reconstruction invalide.':'Invalid reconstruction crop.',
'Cadrage trop petit pour la reconstruction d’aperçu.':'Crop too small for the reconstruction preview.',
'Attendre la fin du traitement avant de changer de bibliothèque.':'Wait for processing to finish before switching libraries.', 'Bibliothèque inconnue.':'Unknown library.',
'Un traitement est déjà en cours.':'Processing is already running.', 'Réglages hors des limites de la démonstration.':'Settings are outside the supported limits.',
'Choisir un intervalle de 1 ou 2 acquisitions.':'Choose an interval of 1 or 2 acquisitions.', 'Une analyse est déjà en cours.':'An analysis is already running.',
'Les résultats ont changé. Actualisez la page.':'Results have changed. Refresh the page.', 'Attendez la fin de l’analyse pour enregistrer une décision.':'Wait for analysis to finish before saving a decision.',
'Filtre inconnu.':'Unknown filter.', 'Aucune analyse disponible.':'No analysis available.', 'Indication introuvable.':'Indication not found.',
'Décision ou commentaire invalide.':'Invalid decision or comment.', 'Aucune image disponible.':'No image available.', 'Image introuvable.':'Image not found.',
'Image hors du jeu de démonstration.':'Image outside the selected dataset.', 'Cette image ne correspond pas aux couches comparées.':'This image does not match the compared layers.',
'Étape 3D inconnue.':'Unknown 3D stage.', 'Cette étape ne fait pas partie de l’analyse.':'This stage is not included in the analysis.', 'Aucune couche mesurée pour cette étape.':'No measured layers for this stage.',
'Zone 3D inconnue.':'Unknown 3D region.', 'La zone prédéfinie sort de cette image.':'The preset region is outside this image.', 'Couche indisponible.':'Layer unavailable.',
'La reconstruction de pièce requiert des photos identifiées après fusion. Étape inconnue pour ces acquisitions.':'Part reconstruction requires identified post-melting photographs. The stage of these acquisitions is unknown.',
'Lancez une analyse pour préparer la reconstruction.':'Run an analysis to prepare the reconstruction.', 'Sélectionnez une couche mesurée après fusion.':'Select a measured post-melting layer.',
'Cette bibliothèque est une série temporelle.':'This library is a time series.', 'Ce job appartient à une autre bibliothèque.':'This job belongs to another library.',
'Photographie introuvable dans ce job.':'Photograph not found in this job.', 'Ce cliché n’est pas voisin de l’indication.':'This photograph is not adjacent to the indication.',
'Dimensions différentes : cadrage commun indisponible.':'Different dimensions: matching crop unavailable.', 'Indication modifiée ou absente.':'Indication changed or missing.',
'Les dimensions de cette image ne permettent pas le cadrage commun.':'Image dimensions do not allow the matching crop.',
'Les annotations des auteurs sont masquées. Utiliser une indication automatique.':'Researcher annotations are hidden. Use an automatically detected indication.',
'Analyse indisponible.':'Analysis unavailable.', 'Requête trop grande ou vide.':'Request too large or empty.',
}
for filename in ['web/index.html','web/stack.js','reporting.py','report_volume.py','review.py','priority.py','persistence.py','libraries.py','inspector.py','job_views.py','job_analysis.py','shape_reconstruction.py','local_app.py']:
    path=ROOT/filename;text=path.read_text(encoding='utf-8')
    for old,new in sorted(MAPPING.items(),key=lambda pair:-len(pair[0])):text=text.replace(old,new)
    path.write_text(text,encoding='utf-8')
